output:
  print-linter-name: true
  sort-results: true

linters:
  enable-all: true
  disable:
    - deadcode
    - depguard
    - dupl
    - exhaustruct
    - exhaustivestruct
    - godot
    - goerr113
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    - wrapcheck
    - varnamelen
    - tagliatelle

linters-settings:
  lll:
      line-length: 120
      tab-width: 4
  cyclop:
    max-complexity: 15
  funlen:
    lines: 120
    statements: 40
    ignore-comments: true
  godox:
    keywords:
      - BUG
      - FIXME
  interfacebloat:
    max: 15
